### PR TITLE
Add the static folder

### PR DESCRIPTION
**Pull request by giswqs**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by kylebarron** [comment]
You can also try with 0.7.0-beta.2, which includes the `MANIFEST.in` file

**Comment by giswqs** [comment]
@kylebarron It seems 0.7.0-beta.2 is working for conda-forge now. I noticed that the `experimental` and `types` are not included in `MANIFEST.IN`. Should they?

image

**Comment by kylebarron** [comment]
Thanks for pushing this over the line!

> @kylebarron It seems 0.7.0-beta.2 is working for conda-forge now. I noticed that the `experimental` and `types` are not included in `MANIFEST.IN`. Should they?

I thought manifest.in was only for including non-standard non-python files. 

If I test installing the 0.7.0-beta.2 conda release, I see the `types` and `experimental` folders:
```
> pixi add lonboard==0.7.0b2
✔ Added lonboard==0.7.0b2
kyle at Kyles-MBP-3 in ~/tmp/lonboard-conda                                9:30
> ls .pixi/envs/default/lib/python3.12/site-packages/lonboard
__init__.py        _geoarrow          _version.py        experimental
__main__.py        _layer.py          _viewport.py       layer_extension.py
_base.py           _map.py            _viz.py            py.typed
_cli.py            _serialization.py  basemap.py         static
_constants.py      _testing.py        colormap.py        traits.py
_environment.py    _utils.py          controls.py        types
```

**Pull request merged**
