### PR TITLE
Add JS build

### PR DESCRIPTION
**Pull request by giswqs**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kylebarron** [comment]
I asked on the anywidget discord and here are two anywidget-based examples for conda: https://github.com/conda-forge/tldraw-feedstock/blob/main/recipe/meta.yaml and https://github.com/conda-forge/staged-recipes/pull/22993. 

Those just pip install the source package into the build environment. Since lonboard doesn't have any native dependencies, I assume that should work here as well. But I think if I'm understanding correctly that pip is only used on the build host, not on the user's machine. Want to try that?

**Comment by giswqs** [comment]
[Here](https://github.com/conda-forge/staged-recipes/pull/24456/files) is the original PR I used to add lonboard to conda-forge. It seems very much similar to the ipyreact recipe. The tldraw feedstock does have add JS in the recipe. I don't know what else needs to be changed.

**Comment by giswqs** [comment]
Here is the error message. It seems the lonboard tar file on PyPI does not contain package.json, causing the conda-forge recipe issue. 

image

**Comment by giswqs** [comment]
I switched the build source from pypi to source. See #9. It was able to build, but the `static` folder is still missing, resulting in `import lonboard` to fail. I am giving up on this. Conda and JS experts are welcome to take over. 

image

**Pull request closed without merging**
